// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import { defineConfig, env } from "prisma/config";

function findProjectRoot(startDir: string): string {
  let dir = startDir;
  for (let i = 0; i < 8; i++) {
    const hasPackageJson = fs.existsSync(path.join(dir, "package.json"));
    const hasPrismaSchema = fs.existsSync(path.join(dir, "prisma", "schema.prisma"));
    if (hasPackageJson && hasPrismaSchema) return dir;

    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return startDir;
}

function normalizeSqliteUrl(databaseUrl: string): string {
  if (!databaseUrl.startsWith("file:")) return databaseUrl;

  const afterPrefix = databaseUrl.slice("file:".length);
  const [filePathPart, ...queryParts] = afterPrefix.split("?");

  // Already absolute (macOS/Linux). Keep as-is.
  if (filePathPart.startsWith("/")) return databaseUrl;

  // Prisma CLI may run from different working directories (e.g., prisma/ when running seed).
  // Resolve relative sqlite paths against the project root to avoid creating prisma/prisma/dev.db.
  const root = findProjectRoot(process.cwd());
  const absolutePath = path.resolve(root, filePathPart);
  const query = queryParts.length ? `?${queryParts.join("?")}` : "";
  return `file:${absolutePath}${query}`;
}

const databaseUrl = normalizeSqliteUrl(env("DATABASE_URL"));

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
