import fs from "node:fs";
import path from "node:path";

type Args = {
  model: string;
  vramGb: number;
  out: string;
  dataset: string;
  sequenceLen?: number;
  flashAttention?: boolean;
};

function parseArgs(argv: string[]): Args {
  const args: Record<string, string> = {};
  for (let i = 0; i < argv.length; i++) {
    const token = argv[i];
    if (!token.startsWith("--")) continue;
    const key = token.slice(2);
    const value = argv[i + 1];
    if (value && !value.startsWith("--")) {
      args[key] = value;
      i++;
    } else {
      args[key] = "true";
    }
  }

  const model = args.model ?? "Qwen/Qwen2.5-7B-Instruct";
  const vramGb = Number(args.vram ?? args.vramGb);
  if (!Number.isFinite(vramGb) || vramGb <= 0) {
    throw new Error(
      "Missing/invalid --vram <GB>. Example: npx tsx scripts/generateAxolotlConfig.ts --vram 6"
    );
  }

  const out = args.out ?? `training/axolotl/generated/qwen2.5-7b-qlora-${vramGb}gb.yaml`;
  const dataset = args.dataset ?? "training_data/prepared/train.jsonl";

  const sequenceLen = args.sequenceLen ? Number(args.sequenceLen) : undefined;
  const flashAttention = args.flashAttention
    ? args.flashAttention === "true"
    : undefined;

  return { model, vramGb, out, dataset, sequenceLen, flashAttention };
}

function chooseProfile(vramGb: number) {
  // Conservative defaults that tend to work across many consumer GPUs.
  // Users can override with --sequenceLen.
  const sequenceLen =
    vramGb <= 6 ? 1024 : vramGb <= 8 ? 2048 : vramGb <= 12 ? 2048 : 4096;

  const loraR = vramGb <= 6 ? 8 : vramGb <= 8 ? 16 : vramGb <= 12 ? 16 : 32;
  const loraAlpha = loraR * 2;

  const microBatchSize = vramGb <= 8 ? 1 : vramGb <= 16 ? 2 : 4;

  // Keep effective batch somewhat stable.
  const targetEffectiveBatch = 16;
  const gradientAccumulationSteps = Math.max(
    4,
    Math.ceil(targetEffectiveBatch / microBatchSize)
  );

  return { sequenceLen, loraR, loraAlpha, microBatchSize, gradientAccumulationSteps };
}

function yamlEscape(value: string) {
  // Quote strings that contain special chars.
  if (/^[A-Za-z0-9_./-]+$/.test(value)) return value;
  return JSON.stringify(value);
}

function renderYaml(cfg: {
  baseModel: string;
  datasetPath: string;
  sequenceLen: number;
  loraR: number;
  loraAlpha: number;
  microBatchSize: number;
  gradientAccumulationSteps: number;
  outputDir: string;
  flashAttention: boolean;
}) {
  return `# Generated by scripts/generateAxolotlConfig.ts
# VRAM profile: ${cfg.outputDir}
# You can override key knobs:
# - sequence_len (1024/2048/4096)
# - micro_batch_size / gradient_accumulation_steps

base_model: ${yamlEscape(cfg.baseModel)}
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

datasets:
  - path: ${yamlEscape(cfg.datasetPath)}
    type: chatml

sequence_len: ${cfg.sequenceLen}
sample_packing: true
pad_to_sequence_len: true

adapter: qlora
lora_r: ${cfg.loraR}
lora_alpha: ${cfg.loraAlpha}
lora_dropout: 0.05
lora_target_linear: true

load_in_4bit: true
bnb_4bit_quant_type: nf4
bnb_4bit_compute_dtype: float16

micro_batch_size: ${cfg.microBatchSize}
gradient_accumulation_steps: ${cfg.gradientAccumulationSteps}
num_epochs: 2
learning_rate: 2.0e-4
lr_scheduler: cosine
warmup_ratio: 0.03

bf16: false
fp16: true
flash_attention: ${cfg.flashAttention ? "true" : "false"}

output_dir: ${yamlEscape(cfg.outputDir)}
save_steps: 200
eval_steps: 200
logging_steps: 10
val_set_size: 0.02
`;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const profile = chooseProfile(args.vramGb);

  const sequenceLen = args.sequenceLen ?? profile.sequenceLen;
  const flashAttention = args.flashAttention ?? false;

  const outputDir = `training/outputs/qwen2.5-7b-qlora-${args.vramGb}gb`;

  const yaml = renderYaml({
    baseModel: args.model,
    datasetPath: args.dataset,
    sequenceLen,
    loraR: profile.loraR,
    loraAlpha: profile.loraAlpha,
    microBatchSize: profile.microBatchSize,
    gradientAccumulationSteps: profile.gradientAccumulationSteps,
    outputDir,
    flashAttention,
  });

  const outPath = path.resolve(process.cwd(), args.out);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, yaml, "utf8");
  console.log(`Wrote Axolotl config: ${args.out}`);
}

main();
